jobs:
  build:
    docker:
      - image: circleci/node:12.13
        environment:
            TEST_DATABASE_URL: postgresql://root@localhost:5432/circle_test
            DB_URL: postgresql://root@localhost:5432/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: 
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            yarn test
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

orbs:
  node: circleci/node@1.1
version: 2.1