jobs:
  build:
    docker:
      - image: circleci/node:12.13
        environment:
            TEST_DATABASE_URL: postgres://root@localhost:5432/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: yarn test
orbs:
  node: circleci/node@1.1
version: 2.1